pipeline {
    agent any

    stages {
        stage('git') {
            steps {
                echo 'Récupération du code...'
                checkout scm
            }
        }

        stage('mvn test') {
            steps {
                dir('student-management') {
                    sh 'mvn test'
                }
            }
        }

        stage('mvn package') {
            steps {
                dir('student-management') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        success { echo 'TOUT EST VERT ! 3 STAGES RÉUSSIS !' }
        failure { echo 'Petit souci de chemin, mais maintenant c\'est bon' }
    }
}